from __future__ import annotations

from typing import Any

import structlog

from src.agents.state import DocumentationState
from src.database import execute
from src.memory.chunking import store_document_chunks
from src.memory.organizational import store_audit_log, store_memory

logger = structlog.get_logger()


def _build_reply_body(state: DocumentationState) -> str:
    """Build the reply comment body for the original source."""
    title = state.get("draft_title", "Untitled")
    doc_type = state.get("doc_type", "unknown")
    confidence = state.get("confidence_score", 0)
    content = state.get("draft_content", "")

    return f"""## Generated Documentation

**Title:** {title}
**Type:** {doc_type}
**Confidence:** {confidence:.0%}

---

{content}

---

*This documentation was automatically generated by [Draftly](https://draftly.ai).*
"""


async def _reply_to_github(state: DocumentationState, metadata: dict) -> None:
    """Reply to a GitHub issue with generated documentation."""
    from src.integrations.github_app import (
        add_issue_labels,
        get_installation_token,
        post_issue_comment,
    )

    installation_id = metadata["installation_id"]
    owner = metadata["owner"]
    repo = metadata["repo"]
    issue_number = metadata["issue_number"]

    token = await get_installation_token(installation_id)
    body = _build_reply_body(state)

    await post_issue_comment(owner, repo, issue_number, body, token)

    labels = [state.get("doc_type", "howto")]
    if state.get("confidence_score", 0) >= 0.7:
        labels.append("high-confidence")
    else:
        labels.append("needs-review")

    await add_issue_labels(owner, repo, issue_number, labels, token)

    logger.info("reply_posted_github", owner=owner, repo=repo, issue=issue_number)


async def _reply_to_slack(state: DocumentationState, metadata: dict) -> None:
    """Reply to a Slack thread with generated documentation."""
    from src.integrations.slack import send_slack_message
    from src.integrations.slack_blocks import build_published_doc_card

    channel = metadata["channel"]
    thread_ts = metadata.get("thread_ts")
    team_id = metadata.get("team_id")

    card = build_published_doc_card(
        title=state.get("draft_title", "Untitled"),
        doc_type=state.get("doc_type", "unknown"),
        confidence=state.get("confidence_score", 0),
        content=state.get("draft_content", ""),
    )

    token = None
    if team_id:
        from src.integrations.slack_store import installation_store

        bot = await installation_store.async_find_bot(
            enterprise_id=None, team_id=team_id,
        )
        if bot:
            token = bot.bot_token

    await send_slack_message(
        channel=channel,
        text=card["text"],
        blocks=card["blocks"],
        thread_ts=thread_ts,
        token=token,
    )

    logger.info("reply_posted_slack", channel=channel, thread_ts=thread_ts)


_DISCORD_MAX_LENGTH = 2000


def _build_discord_reply_chunks(state: DocumentationState) -> list[str]:
    """Build reply messages that fit within Discord's message character limit."""
    title = state.get("draft_title", "Untitled")
    doc_type = state.get("doc_type", "unknown")
    confidence = state.get("confidence_score", 0)
    content = state.get("draft_content", "")

    header = (
        f"## Generated Documentation\n\n"
        f"**Title:** {title}\n"
        f"**Type:** {doc_type}\n"
        f"**Confidence:** {confidence:.0%}\n\n"
        f"---\n\n"
    )
    footer = (
        "\n\n---\n\n"
        "*This documentation was automatically generated by "
        "[Draftly](https://draftly.ai).*"
    )

    # Single message fits
    full_body = header + content + footer
    if len(full_body) <= _DISCORD_MAX_LENGTH:
        return [full_body]

    # Split content at paragraph boundaries and pack into messages
    paragraphs = content.split("\n\n")
    messages: list[str] = []
    current = header

    for para in paragraphs:
        sep = "" if current == header else "\n\n"
        addition = sep + para
        if len(current) + len(addition) <= _DISCORD_MAX_LENGTH:
            current += addition
        else:
            # Flush current message
            if current != header:
                messages.append(current)
            # If single paragraph exceeds limit, hard-split it
            if len(para) > _DISCORD_MAX_LENGTH:
                remaining_para = para
                while remaining_para:
                    chunk = remaining_para[:_DISCORD_MAX_LENGTH]
                    remaining_para = remaining_para[_DISCORD_MAX_LENGTH:]
                    if remaining_para:
                        messages.append(chunk)
                    else:
                        current = chunk
            else:
                current = para

    # Append footer to last message (or start a new one if it won't fit)
    if current:
        if len(current) + len(footer) <= _DISCORD_MAX_LENGTH:
            messages.append(current + footer)
        else:
            messages.append(current)
            messages.append(footer)
    elif messages:
        last = messages[-1]
        if len(last) + len(footer) <= _DISCORD_MAX_LENGTH:
            messages[-1] = last + footer
        else:
            messages.append(footer)

    return messages


async def _reply_to_discord(state: DocumentationState, metadata: dict) -> None:
    """Reply to a Discord thread with generated documentation."""
    from src.integrations.discord import send_discord_thread_reply

    raw_thread_id = metadata.get("thread_id") or metadata.get("channel_id")
    if raw_thread_id is None:
        logger.warning("reply_skipped_discord_no_thread_id", metadata=metadata)
        return

    thread_id = str(raw_thread_id)
    chunks = _build_discord_reply_chunks(state)

    logger.info(
        "discord_reply_target",
        thread_id=thread_id,
        chunk_count=len(chunks),
        total_length=sum(len(c) for c in chunks),
        metadata_thread_id=metadata.get("thread_id"),
        metadata_channel_id=metadata.get("channel_id"),
        metadata_message_id=metadata.get("message_id"),
    )

    for i, chunk in enumerate(chunks):
        await send_discord_thread_reply(thread_id=thread_id, content=chunk)
        logger.info("discord_reply_chunk_sent", thread_id=thread_id, chunk=i + 1, total=len(chunks))


async def publish_node(state: DocumentationState) -> dict:
    org_id = state["org_id"]
    doc_id = state.get("doc_id", "")
    content = state.get("draft_content", "")
    title = state.get("draft_title", "")

    logger.info("publish_started", org_id=org_id, doc_id=doc_id)

    # 1. Update documentation status
    await execute(
        "UPDATE documentation SET status = 'approved', updated_at = now() WHERE id = $1",
        doc_id,
    )

    # 2. Store chunked embeddings for future semantic search
    await store_document_chunks(
        org_id=org_id,
        content_id=doc_id,
        title=title,
        content=content,
        metadata={"doc_type": state.get("doc_type"), "confidence": state.get("confidence_score")},
    )

    # 3. Store in organizational memory
    await store_memory(
        org_id=org_id,
        memory_type="organizational",
        key=title,
        value={
            "doc_id": doc_id,
            "content": content[:1000],
            "doc_type": state.get("doc_type"),
            "confidence": state.get("confidence_score"),
        },
        source="documentation_generation",
        confidence=state.get("confidence_score", 0.5),
    )

    # 4. Store reviewer feedback if present
    if state.get("human_feedback"):
        await store_memory(
            org_id=org_id,
            memory_type="reviewer",
            key=f"review_{doc_id}",
            value={
                "feedback": state["human_feedback"],
                "decision": state.get("human_decision"),
                "doc_title": title,
            },
            source="human_review",
            confidence=1.0,
        )

    # 5. Mark support thread as resolved
    await execute(
        """
        UPDATE support_threads
        SET status = 'resolved', resolution = $1, resolved_at = now()
        WHERE id = $2
        """,
        content[:2000],
        state.get("support_thread_id"),
    )

    # 6. Audit log
    await store_audit_log(
        org_id=org_id,
        actor="agent",
        action="publish_documentation",
        resource_type="documentation",
        resource_id=doc_id,
        details={"title": title, "confidence": state.get("confidence_score")},
    )

    # 7. Reply to original source
    source = state.get("source", "cli")
    metadata = state.get("source_metadata", {})
    published_urls: list[dict[str, Any]] = [{"platform": "draftly", "doc_id": doc_id}]
    reply_errors = []

    try:
        if source == "github" and metadata:
            await _reply_to_github(state, metadata)
            issue_num = str(metadata.get("issue_number", ""))
            published_urls.append({"platform": "github", "issue": issue_num})
        elif source == "slack" and metadata:
            await _reply_to_slack(state, metadata)
            channel = str(metadata.get("channel", ""))
            published_urls.append({"platform": "slack", "channel": channel})
        elif source == "discord" and metadata:
            await _reply_to_discord(state, metadata)
            thread = str(metadata.get("thread_id", ""))
            published_urls.append({"platform": "discord", "thread": thread})
    except Exception as e:
        reply_errors.append({"platform": source, "error": str(e)})
        logger.error("reply_failed", source=source, error=str(e))

    logger.info("publish_completed", doc_id=doc_id, title=title, source=source)

    return {
        "published_urls": published_urls,
        "reply_errors": reply_errors,
        "human_decision": "",
        "human_feedback": "",
    }
