from __future__ import annotations

import structlog
from langchain_cockroachdb import AsyncCockroachDBSaver  # type: ignore[import-untyped]
from langchain_core.runnables import RunnableConfig

from src.agents.graph import build_hybrid_graph
from src.agents.state import DocumentationState
from src.config import settings
from src.integrations.github_app import post_issue_comment
from src.memory.organizations import (
    get_org_by_github,
    link_workflow_to_document,
    store_github_installation,
    store_github_workflow,
    update_github_workflow_status,
)

logger = structlog.get_logger()


def build_github_state(payload: dict, org_id: str) -> DocumentationState:
    """Build initial DocumentationState from GitHub issue data."""
    issue = payload["issue"]
    repo = payload["repository"]

    question = f"{issue['title']}\n\n{issue.get('body', '')}"

    graph_thread_id = f"github-{repo['id']}-{issue['number']}"

    return {
        "org_id": org_id,
        "source": "github",
        "channel_id": repo["full_name"],
        "thread_id": str(issue["number"]),
        "graph_thread_id": graph_thread_id,
        "question": question,
        "similar_threads": [],
        "existing_docs": [],
        "reviewer_feedback_history": [],
        "semantic_context": [],
        "github_context": [],
        "slack_context": [],
        "knowledge_package": {},
        "draft_content": "",
        "draft_title": "",
        "doc_type": "howto",
        "confidence_score": 0.0,
        "review_result": {},
        "review_feedback": "",
        "rubric_feedback": "",
        "rubric_evaluations": [],
        "human_decision": "",
        "human_feedback": "",
        "published_urls": [],
        "reply_errors": [],
        "support_thread_id": "",
        "workflow_id": "",
        "doc_id": "",
        "messages": [],
        "source_metadata": {
            "installation_id": payload["installation"]["id"],
            "owner": repo["owner"]["login"],
            "repo": repo["name"],
            "issue_number": issue["number"],
        },
        "message_history": [],
        "question_type": "unknown",
        "research_skill": {},
        "investigation_plan": [],
        "rubric_status": {},
        "subagent_results": {},
        "_node_traces": [],
        "_trace_collected": False,
        "episode_id": "",
        "reflection_id": "",
        "_reflected": False,
    }


async def post_error_comment(
    owner: str, repo: str, issue_number: int, token: str, error: str
) -> None:
    """Post an error comment to GitHub issue."""
    comment_body = f"""## Documentation Generation Failed

An error occurred while generating documentation for this issue:

```
{error}
```

Please try again or contact support.

---
*This comment was automatically generated by [Draftly](https://draftly.ai)*
"""
    await post_issue_comment(owner, repo, issue_number, comment_body, token)


async def run_github_pipeline(payload: dict, installation_token: str) -> None:
    """Orchestrate the full Draftly pipeline for a GitHub issue."""
    from src.database import close_pool, get_pool

    await get_pool()

    try:
        issue = payload["issue"]
        repo = payload["repository"]
        owner = repo["owner"]["login"]
        repo_name = repo["name"]
        installation_id = payload["installation"]["id"]

        org = await get_org_by_github(repo["owner"]["login"])
        if not org:
            github_org = repo["owner"]["login"]
            error_msg = (
                f"Organization '{github_org}' not found. "
                "Create it via Clerk first."
            )
            logger.error("github_pipeline_org_not_found", github_org=github_org)
            await post_error_comment(
                owner, repo_name, issue["number"], installation_token, error_msg
            )
            return
        org_id = org["id"]

        await store_github_installation(
            org_id=org_id,
            installation_id=installation_id,
            github_org=repo["owner"]["login"],
        )

        state = build_github_state(payload=payload, org_id=org_id)

        config: RunnableConfig = {
            "configurable": {"thread_id": f"github-{repo['id']}-{issue['number']}"}
        }

        async with AsyncCockroachDBSaver.from_conn_string(settings.cockroachdb_url) as checkpointer:
            await checkpointer.setup()
            graph = build_hybrid_graph().compile(checkpointer=checkpointer)

            from uuid import uuid4

            workflow_id = str(uuid4())
            state["workflow_id"] = workflow_id
            await store_github_workflow(
                org_id=org_id,
                workflow_id=workflow_id,
                installation_id=installation_id,
                owner=owner,
                repo=repo_name,
                issue_number=issue["number"],
            )

            await update_github_workflow_status(workflow_id, "running")

            structlog.contextvars.bind_contextvars(workflow_id=workflow_id, org_id=org_id)
            try:
                result = await graph.ainvoke(state, config)

                if result.get("human_decision") == "":
                    await update_github_workflow_status(workflow_id, "pending")
                    logger.info(
                        "github_pipeline_paused",
                        owner=owner,
                        repo=repo_name,
                        issue=issue["number"],
                    )
                else:
                    await update_github_workflow_status(workflow_id, "completed")

                if result.get("doc_id"):
                    await link_workflow_to_document(workflow_id, result["doc_id"])
            finally:
                structlog.contextvars.clear_contextvars()

    except Exception as e:
        logger.error("github_pipeline_failed", error=str(e), exc_info=True)
        try:
            await post_error_comment(owner, repo_name, issue["number"], installation_token, str(e))
        except Exception:
            logger.error("failed_to_post_error_comment", owner=owner, repo=repo_name)
    finally:
        await close_pool()
